@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION

SET CURRNET_DIR=%~dp0
SET SOLUTION_FILE=%CURRENT_DIR%ModRSsim2016\ModRSsim2016.sln
SET TARGETS=Release_x86 Debug_x86 Release_x64 Debug_x64
SET DEFAULT_ACTION=build
SET BUILDER=devenv


SET ACTION=
:PARAMETERS
IF "%1"=="" GOTO ACTIONS
SET ACTION=%ACTION%%1 
SHIFT
GOTO PARAMETERS

:ACTIONS:
IF "%ACTION%"=="" SET ACTION=%DEFAULT_ACTION%
ECHO Solution: %SOLUTION_FILE%
ECHO Actions : %ACTION%
ECHO Targets : %TARGETS%
FOR %%F IN (%ACTION%) DO (
	FOR %%G IN (%TARGETS%) DO (
		ECHO Current Action: "%%F" of "%SOLUTION_FILE%" for"%%G"
		%BUILDER% %SOLUTION_FILE% /%%F %%G
	)
)

ENDLOCAL